---

- name: installing ufw
  package:
    name:  '{{ item }}'
    state: present
  with_items:
    - ufw

  when: ansible_os_family =='Debian' or ansible_os_family =='Ubuntu'



- name: Installing firewalld package
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - firewalld

  when: ansible_os_family =='RedHat'


- name: Installing iptables
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - iptables
  when: ansible_os_family =='Kali'